name: valsai_github_action
description: 'Vals AI Github Action'
inputs:
  vals_api_key:
    description: "VALS AI Api Key (created in the Admin Console)"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    # Install any local requirements
    - run: pip install -r requirements.txt
      shell: bash
    # Make sure vals is installed at minimum
    - run: pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash
    - id: run
      run: |
        echo 'script_out<<EOF' >> $GITHUB_OUTPUT
        python  ${GITHUB_ACTION_PATH}/script.py >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash
      env:
        VALS_API_KEY: ${{ inputs.vals_api_key }}
    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${{steps.run.outputs.script_out}}` 
          })
